PORT: 11001

# DB Config
DATABASE_HOST: GO_DATABASE_HOST
DATABASE_PORT: GO_DATABASE_PORT
DATABASE_USER: GO_DATABASE_USER
DATABASE_PASSWORD: GO_DATABASE_PASSWORD
DATABASE_NAME: GO_DATABASE_NAME

# JWT Config
JWT_SECRET : secret
